server:
  port: 8001

spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://172.31.18.111:3306/account
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://172.31.18.111:8070/eureka/

info:
  app:
    name: "account"
    description: "InChemi Account Application"
    version: "1.0.0"