server:
  port: 8002
spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://localhost:3306/molecule
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "molecule"
    description: "InChemi Molecule Application"
    version: "1.0.0"