server:
  port: 8002
spring:
  application:
    name: molecule
  datasource:
    url: jdbc:mysql://18.218.70.221:3306/molecule
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://172.31.26.13:8070/eureka/

info:
  app:
    name: "molecule"
    description: "InChemi Molecule Application"
    version: "1.0.0"