server:
  port: 8070

eureka:
  instance:
    hostname: 172.31.26.13
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/