server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://172.31.18.111:8070/eureka/"

spring:
  application:
    name: "gateway"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://172.31.18.111:7080/realms/master/protocol/openid-connect/certs"


  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gateway"
    description: "InChemi Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    org:
      threeam: DEBUG

